### PR TITLE
feat(shape-55): add default slot to the SbHeaderTitle component

### PR DESCRIPTION
**Pull request by emanuelgsouza**
## Pull request type

Jira Link: [SHAPE-55](https://storyblok.atlassian.net/browse/SHAPE-55)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

Nothing should be changed in the SbHeaderTitle component. The PR adds support for a default slot in this component.

## Other information

[SHAPE-55]: https://storyblok.atlassian.net/browse/SHAPE-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by marcosh-ramos — APPROVED** [review]
LGTM!

**Comment by fariacc** [comment]
@emanuelgsouza could you check why the unit test is failing?

**Comment by emanuelgsouza** [comment]
Hey @fariacc. It is an error related to the node-engine. @marcosh-ramos changed it to his PR. We can merge his PR first, then check in mine if everything is ok.

**Comment by emanuelgsouza** [comment]
All the checks passing now @fariacc.

**Review by fariacc — APPROVED** [review]

**Pull request merged**
