### PR TITLE
bugfix(int-377): Removing border + Removing automatic aperture from slide over

### PR DESCRIPTION
**Pull request by ademarCardoso**
## Pull request type

Jira Link: [INT-622](https://storyblok.atlassian.net/browse/INT-622) + [INT-377](https://storyblok.atlassian.net/browse/INT-377)

- [x] Bugfix

## How to test this PR

In the video below you can see that I show the two problems that were solved in this PR, one is the double border in the date piker time selection and the other is that the lside over opened automatically, and that was removed.

For more information please check the task descriptions.

https://user-images.githubusercontent.com/40925579/198716362-6a2e6180-7719-4161-9b63-56f584725282.mov

## What is the new behavior?

- Slideover does not automatically open in documentation
- Removed the double border appearance of the time picker in datepicker

### CODE REVIEW

**Review by fariacc — APPROVED** [review]

**Review by FidalgoMonica — COMMENTED** [review]
Hi @ademarCardoso great job! I just noticed that we still have a double border at the beginning, please check the video, but it's because we have an overlay of borders, I was thinking, maybe we can change the height a little and this will solve that, what do you think? :)


https://user-images.githubusercontent.com/94900845/199467682-dca354bc-4ce6-441c-adda-7661ef4f022e.mov

**Review by fernandacanto — APPROVED** [review]
Good job!

**Review by FidalgoMonica — APPROVED** [review]
@ademarCardoso tests are failing. after fixing that I think we can merge :)

**Comment by ademarCardoso** [comment]
> @ademarCardoso tests are failing. after fixing that I think we can merge :)

The error is about node version, has anyone had this problem? I updated but on my machine the problem does not appear

**Comment by lisilinhart** [comment]
> > @ademarCardoso tests are failing. after fixing that I think we can merge :)
> 
> The error is about node version, has anyone had this problem? I updated but on my machine the problem does not appear

I will check Ademar

**Pull request merged**
