### PR TITLE
feat(FT-376): Add the anchor icon

### PR DESCRIPTION
**Pull request by mmatheuspalma**
We need to add the Anchor icon to the DS

## Pull request type

Jira Link: [FT-376](https://storyblok.atlassian.net/browse/FT-376)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR
- Check if the icon is rendered correctly

## What is the new behavior?
- Anchor icon added

## Other information

[FT-376]: https://storyblok.atlassian.net/browse/FT-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Moragwa-Brenda** [comment]
Hello @mmatheuspalma, I logged in to the design system using the link but I could not see the anchor icon. Are there other steps to check this?
image

**Review by fariacc — APPROVED** [review]

**Comment by fariacc** [comment]
> Hello @mmatheuspalma, I logged in to the design system using the link but I could not see the anchor icon. Are there other steps to check this? image

Hey @Moragwa-Brenda it's here https://storyblok-design-system-git-feat-adding-an-c796a4-storyblok-com.vercel.app/?path=/story/design-system-components-sbicon--all-icons

**Comment by Moragwa-Brenda** [comment]
> > Hello @mmatheuspalma, I logged in to the design system using the link but I could not see the anchor icon. Are there other steps to check this? image
> 
> Hey @Moragwa-Brenda it's here https://storyblok-design-system-git-feat-adding-an-c796a4-storyblok-com.vercel.app/?path=/story/design-system-components-sbicon--all-icons

Thanks Caro

**Review by Moragwa-Brenda — APPROVED** [review]
I checked the anchor icon, its okay. Good progress @mmatheuspalma 
image

**Review by fernandacanto — APPROVED** [review]

**Pull request merged**
