### PR TITLE
INT-104[bugfix]: fix avatar and icon fallback empty nodes

### PR DESCRIPTION
**Pull request by fernandacanto**
This PR is needed to fix the empty nodes on two components SbIcon and SbAvatar.

## Pull request type

Jira Link: [INT-104 - Design System - Empty nodes on blok.ink](https://storyblok.atlassian.net/browse/INT-104)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

In Menu > Components > SbAvatar > With Fallback
Check that the icons is displayed.

In Menu > Components > SbIcon > Fallback Icon
Check that the icon is displayed.

## Other information
Any problem I'm available!

### CODE REVIEW

**Comment by thiagosaife** [comment]
Fernanda. The empty nodes was fixed, but the fallback images are not being shown for both avatar and icon, like the image bellow:
Screen Shot 2022-02-01 at 09 53 47

Screen Shot 2022-02-01 at 09 55 15

**Review by thiagosaife — CHANGES_REQUESTED** [review]
I leave a comment about the fallback's images not being shown.

**Review by thiagosaife — APPROVED** [review]
As we spoke on daily today, these errors are being fixed when merged with master branch.

**Review by ademarCardoso — APPROVED** [review]
Works great 😄

**Pull request merged**
