### PR TITLE
chore: icon updates from Nikola

### PR DESCRIPTION
**Pull request by lisilinhart**
## Pull request type

Jira Link: -

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Other (please describe): Some icons are replaced with new ones

## How to test this PR

Check the app with these icons, you can find the preview link in the storyfront repository as a pull request

image

You can also check the updated icons in the storybook: https://storyblok-design-system-git-chore-icon-updates-storyblok-com.vercel.app/?path=/docs/design-system-components-sbicon--default#all-icons

## What is the new behavior?

- icons replaces
- 
-

### CODE REVIEW

**Review by FidalgoMonica — COMMENTED** [review]
Hi @lisilinhart I have a question about the comment and folder icons, are they supposed to be filled? since we also have the same but "filled" 

Captura de ecrã 2022-10-26, às 16 41 09

**Comment by FidalgoMonica** [comment]
> Hi @lisilinhart I have a question about the comment and folder icons, are they supposed to be filled? since we also have the same but "filled"
> 
> Captura de ecrã 2022-10-26, às 16 41 09

Updated

**Comment by FidalgoMonica** [comment]
Need to remove:
- clipboard icon (is not needed)
- link-url ( we will use the link instead)

**Review by fariacc — APPROVED** [review]
I took a look and all icons seems fine ;)

**Review by FidalgoMonica — APPROVED** [review]

**Review by marcosh-ramos — APPROVED** [review]

**Pull request merged**
