### PR TITLE
task(work-377): introduce sticky menu option to SbDataTable

### PR DESCRIPTION
**Pull request by vcpablo**
Introduce _sticky menu_ prop to `SbDataTable`
**This may still have some design change. cc: @nmilasinovic**

## Pull request type

Jira Link: [WORK-377](https://storyblok.atlassian.net/browse/WORK-377)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR
1. Make sure that, when adding the `sticky-menu` prop as `true` when using the component will make the actions menu (displayed when at least one row is selected) to be fixed at the top of the table, when scrolling it down.
2. Make sure that the new changes do not affect the `SbDataTable` nor `SbDataTableActions` component layout when `sticky-menu` is false _(default)_

**For `sticky-menu` prop to make sense, `allow-selection` prop must also be true**

## What is the new behavior?

- Now, when setting `sticky-menu` prop  to `true` when using the component, the actions menu will be fixed at the top when scrolling down.

### CODE REVIEW

**Review by fernandacanto — COMMENTED** [review]
Hey @vcpablo the code is nice and works great but when selecting an item from the table we check 3 items. I know you tripled the data JSON to make testing easier, but if you could add other items it would be better. If it's too much work we can keep it that way, what do you think?


https://user-images.githubusercontent.com/8209305/178554777-e823073e-4f92-423f-94fd-a037ae8d95b9.mov



Uploading Gravação de Tela 2022-07-12 às 14.21.07.mov…

**Comment by vcpablo** [comment]
> Hey @vcpablo the code is nice and works great but when selecting an item from the table we check 3 items. I know you tripled the data JSON to make testing easier, but if you could add other items it would be better. If it's too much work we can keep it that way, what do you think?
> 
>  Gravacao.de.Tela.2022-07-12.as.14.21.07.mov 
> Uploading Gravação de Tela 2022-07-12 às 14.21.07.mov…

Done ✅

**Review by fernandacanto — APPROVED** [review]
Good job!

**Review by emanuelgsouza — APPROVED** [review]
Nice job

**Pull request merged**
