### PR TITLE
feat(avatar): refactor avatar to single file component

### PR DESCRIPTION
**Pull request by vcpablo**
Refactor `SbAvatar` as a _single file component_

## Pull request type

Jira Link: [WORK-166](https://storyblok.atlassian.net/browse/WORK-166)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## What is the new behavior?

- Refactor `SbAvatar` as a _single file component_

### CODE REVIEW

**Review by fernandacanto — CHANGES_REQUESTED** [review]
Hey @vcpablo, check the unit tests as they are failing... 🪲

**Review by fernandacanto — APPROVED** [review]

**Comment by vcpablo** [comment]
> Exist a design change in SbAvatarGroup, see on the video bellow, it's expected ?
> 
>  Screen.Recording.2022-05-18.at.11.27.46.mov

Good catch, @ademarCardoso , I've just addressed this issue

**Review by fernandacanto — CHANGES_REQUESTED** [review]
Hey @vcpablo all checks have failed. 😢

**Review by ademarCardoso — APPROVED** [review]
Now it's working really better 😄

**Review by fernandacanto — APPROVED** [review]

**Pull request merged**
