### PR TITLE
Task(on-324): Activate new tab link on the sidebar

### PR DESCRIPTION
**Pull request by FidalgoMonica**
## Pull request type

Jira Link: [ON-324](https://storyblok.atlassian.net/browse/ON-324)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

- Open a space (it has more links on side bar)
- Right-click with mouse on a sidebar link and see that you have an option to open that in a new window

## Other information

This PR removes href binding for router-link because it was overriding router-link generated value as soon as we click on a sidebar list item
Captura de ecrã 2022-03-29, às 10 51 08

Video:

https://user-images.githubusercontent.com/94900845/160793594-526dc52a-346c-478f-a596-a721b6b212b7.mov

### CODE REVIEW

**Comment by FidalgoMonica** [comment]
> I don't know if we really need to remove the "href" from the ListItem here in the Design System, I think we can add the "required: false", to maintain compatibility. This project is open source and we may have users who don't use router-link.

@fariacc @fernandacanto for me that didnt work. I was testing the sidebar on storyfront and as soon as I click another element on the sidebar, it loses the href generated by :to .. since the href is overriding the href from router-link, even with the required false

**Comment by FidalgoMonica** [comment]
Without the :href on the ListItem, check the url that appears on the left bottom

https://user-images.githubusercontent.com/94900845/160805220-32fc06d7-0914-4b72-b3c5-cc08a873cf44.mov

**Comment by FidalgoMonica** [comment]
With the :href, check that we dont have links or the possibility to open in new window

https://user-images.githubusercontent.com/94900845/160805780-47ae2d00-0ec3-4a9a-83c5-1a00b56d5354.mov

**Comment by FidalgoMonica** [comment]
@fernandacanto @fariacc, @lisilinhart did improvements on the pr with the if else approach :) please re-check

**Comment by lisilinhart** [comment]
> @FidalgoMonica and @lisilinhart, the work is great, but when minimizing the sidebar there is some component blinking. I recorded a video showing the problem.
> Gravacao.de.Tela.2022-03-30.as.09.45.45.mov

Go catch Fernanda, I will check again

**Review by fernandacanto — APPROVED** [review]
Nice work! 💪🏻

**Pull request merged**
