### PR TITLE
Bugfix: keep the span tag when button has loading state

### PR DESCRIPTION
**Pull request by fariacc**
## Pull request type

Jira Link: [INT-](url)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

You can checkout your DS branch to this PR's branch and test the loading buttons of Storyblok app locally. Here are some examples:

https://user-images.githubusercontent.com/26799272/181383743-f9e74f59-5d19-464f-8bde-ade4f15e49b4.mov

## What is the new behavior?

- Keeping the span element which makes the button to the keep the correct height
- 
-

### CODE REVIEW

**Review by thiagosaife — APPROVED** [review]
Nicely done! Thanks for the help.

**Comment by thiagosaife** [comment]
@fariacc Don't bother about the unit test error. It's not related to this fix.

**Review by anthonysousa — APPROVED** [review]
Well done, Carol!

**Review by lisilinhart — APPROVED** [review]
Great work Caro, I tested with the app and the bug is fixed 💪

**Pull request merged**
